import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import ErrorBoundary from "@/components/error-boundary";
import "./globals.css";
import { Toaster } from "@/components/ui/toaster";
import { CodeFileProvider } from "../components/code-file-provider";
import ConnectionStyles from "@/components/connection-styles";
import { NavTabs } from "@/components/nav-tabs";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  display: "swap",
  preload: false,
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
  display: "swap",
  preload: false,
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  display: "swap",
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${inter.variable} antialiased relative overflow-x-hidden`}
        suppressHydrationWarning={true}
      >
        <ConnectionStyles />
        <NavTabs />
        <ErrorBoundary>
          <CodeFileProvider>
            <div className="pt-16">{children}</div>
          </CodeFileProvider>
        </ErrorBoundary>
        <Toaster />
      </body>
    </html>
  );
}
